spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
server:
  servlet:
    context-path: /file
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

file:
  path: D:/file/grady/course/
  domain: http://127.0.0.1:9000/file/f/
