spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
server:
  servlet:
    context-path: /file
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

file:
  path: D:/file/grady/course/
  domain: http://127.0.0.1:9000/file/f/

#oss
accessKeyId: LTAI4GKCEgGRvFBxkwzLpv2c
accessKeySecret: VoeKD8tF3RNqxLe3BhtcfLXeAq0Rxo
endpoint: http://oss-cn-shanghai.aliyuncs.com
ossDomain: http://grady.oss-cn-shanghai.aliyuncs.com/
bucket: grady