spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradycource?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    com:
      grady:
        server:
          mapper: trace

mybatis:
  mapper-locations: classpath:/mapper/*.xml