spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          predicates:
            - args:
                - /system/**
              name: Path
          uri: http://127.0.0.1:9001
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
