spring:
  cloud:
    gateway:
      routes:
        -   id: system
            predicates:
              -   args:
                    - /system/**
                  name: Path
            uri: http://127.0.0.1:9001
        -   id: business
            predicates:
              -   args:
                    - /business/**
                  name: Path
            uri: http://127.0.0.1:9002
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
