eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - filters:
        - args:
          - true
          name: LoginAdmin
        id: system
        predicates:
        - args:
          - /system/**
          name: Path
        uri: http://127.0.0.1:9001
      - filters:
        - args:
          - true
          name: LoginAdmin
        id: business
        predicates:
        - args:
          - /business/**
          name: Path
        uri: http://127.0.0.1:9002
      - filters:
        - args:
          - true
          name: LoginAdmin
        id: file
        predicates:
        - args:
          - /file/**
          name: Path
        uri: lb://file
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    password: Redis000
    port: 6379
